//Creado con Ardora - www.webardora.net
//bajo licencia Attribution-NonCommercial-NoDerivatives 4.0 International (CC BY-NC-ND 4.0)
//para otros usos contacte con el autor
function initAct(){
if (tiAval){parent.iniciaActividade()}if ((tiTime) && (tiButtonTime)){paintButtonTime();}
document.addEventListener("touchstart", touchHandler, true);document.addEventListener("touchmove", touchHandler, true);document.addEventListener("touchend", touchHandler, true);document.addEventListener("touchcancel", touchHandler, true);
paintGrid();$(".divpiece").css({left:(celsize*col+celsize/2)+"px",top:(celsize*fil-celsize*4)+"px"});
}
function paintGrid(){if (celsize*5< (solw + 2) * celsize / 2){var n_w=celsize*col+(solw+2)*celsize / 2;}else{var n_w=celsize*col + celsize*5;}$("#svggrid").css("width",n_w);$("#svggrid").css("height",celsize*(fil));$("#svggrid").attr("viewBox", "0 0 " + n_w + " " + celsize*fil);$("#svggrid").attr("preserveAspectRatio", "xMinYMin meet");
var vgrid = document.createElementNS("http://www.w3.org/2000/svg","g");var $vgrid= $(vgrid);$vgrid.attr("id","gridgame");$vgrid.attr("fill",colorBack);document.getElementById("svggrid").appendChild(vgrid);
for (i=0;i<fil+1;i++){$(document.createElementNS("http://www.w3.org/2000/svg","line")).attr({x1:0,y1:i*celsize,x2:col*celsize,y2:i*celsize}).appendTo("#gridgame");}
for (i=0;i<col+1;i++){$(document.createElementNS("http://www.w3.org/2000/svg","line")).attr({x1:i*celsize,y1:0,x2:i*celsize,y2:fil*celsize}).appendTo("#gridgame");}
paintshow();
var colpieces=0;var filpieces=0;topinitial=$("#svggrid").offset().top;leftinitial=0
paintpiece("1_1","#FF8000");paintpiece("2_1","#FF8000");paintpiece("3_1","#FF8000");paintpiece("4_1","#FF8000");paintpiece("5_1","#FF8000");paintpiece("6_1","#FF8000");paintpiece("7_1","#FF8000");paintpiece("8_1","#FF8000");paintpiece("9_1","#FF8000");paintpiece("10_1","#FF8000");paintpiece("11_1","#FF8000");paintpiece("12_1","#FF8000");}
function paintshow() {var tam=celsize/2;var marg=(col+1)*celsize;for (i = 0; i < solw; i++) {for (j = 0; j < solh; j++) {var a = PentaWords(sol[j][i]).toString().trim();
if (a.localeCompare("N")!=0) {var rect = document.createElementNS("http://www.w3.org/2000/svg", "rect");rect.setAttributeNS(null,"x",marg+i*tam);rect.setAttributeNS(null,"y",j*tam );rect.setAttributeNS(null,"height",tam);rect.setAttributeNS(null,"width",tam);rect.setAttribute("class","c_show");document.getElementById("gridgame").appendChild(rect);}}}
for (i = 0; i < solw; i++) {for (j = 0; j < solh; j++) {var a = PentaWords(sol[j][i]).toString().trim();
if (a.localeCompare("N") != 0) {if (i == 0) {var line = document.createElementNS("http://www.w3.org/2000/svg", "line");line.setAttributeNS(null, "x1",marg+ i * tam );line.setAttributeNS(null, "y1", j * tam );line.setAttributeNS(null, "x2",marg+ i * tam );line.setAttributeNS(null, "y2", j * tam + tam);line.setAttribute("class", "c_showline");document.getElementById("gridgame").appendChild(line);} else {
var b=PentaWords(sol[j][i-1]).toString().trim();var line=document.createElementNS("http://www.w3.org/2000/svg", "line");line.setAttributeNS(null, "x1",marg+ i * tam);line.setAttributeNS(null, "y1", j * tam);line.setAttributeNS(null, "x2",marg+ i * tam);line.setAttributeNS(null, "y2", j * tam + tam);line.setAttribute("class", "c_showline");if (a.localeCompare(b) != 0) {document.getElementById("gridgame").appendChild(line);}}
if (i==solw-1) {var line=document.createElementNS("http://www.w3.org/2000/svg", "line");line.setAttributeNS(null, "x1",marg+i*tam+tam);line.setAttributeNS(null,"y1",j*tam);line.setAttributeNS(null, "x2",marg+i*tam+tam);line.setAttributeNS(null,"y2",j*tam+tam);line.setAttribute("class", "c_showline");document.getElementById("gridgame").appendChild(line);
} else {var c=PentaWords(sol[j][i+1]).toString().trim();var line=document.createElementNS("http://www.w3.org/2000/svg", "line");line.setAttributeNS(null,"x1",marg+i*tam+tam);line.setAttributeNS(null,"y1",j*tam);line.setAttributeNS(null,"x2",marg+i*tam+tam);line.setAttributeNS(null,"y2",j*tam+tam);line.setAttribute("class","c_showline");if (a.localeCompare(c)!=0) {document.getElementById("gridgame").appendChild(line);}}
if (j == 0) {var line=document.createElementNS("http://www.w3.org/2000/svg", "line");line.setAttributeNS(null,"x1",marg+i*tam);line.setAttributeNS(null,"y1",j*tam);line.setAttributeNS(null,"x2",marg+i*tam+tam);line.setAttributeNS(null,"y2",j*tam );line.setAttribute("class","c_showline");document.getElementById("gridgame").appendChild(line);
} else {var b=PentaWords(sol[j-1][i]).toString().trim();var line=document.createElementNS("http://www.w3.org/2000/svg","line");line.setAttributeNS(null,"x1",marg+i*tam);line.setAttributeNS(null,"y1",j*tam);line.setAttributeNS(null,"x2",marg+i*tam+tam);line.setAttributeNS(null,"y2",j*tam);line.setAttribute("class","c_showline");if (a.localeCompare(b)!=0) {document.getElementById("gridgame").appendChild(line);}}
if (j==solh-1) {var line=document.createElementNS("http://www.w3.org/2000/svg", "line");line.setAttributeNS(null,"x1",marg+i*tam);line.setAttributeNS(null,"y1",j*tam+tam);line.setAttributeNS(null,"x2",marg+i*tam+tam);line.setAttributeNS(null,"y2",j*tam+tam);line.setAttribute("class", "c_showline");document.getElementById("gridgame").appendChild(line);
} else {var d=PentaWords(sol[j+1][i]).toString().trim();var line=document.createElementNS("http://www.w3.org/2000/svg", "line");line.setAttributeNS(null,"x1",marg+i*tam);line.setAttributeNS(null,"y1",j*tam+tam);line.setAttributeNS(null,"x2",marg+i*tam+tam);line.setAttributeNS(null,"y2",j*tam+tam);line.setAttribute("class","c_showline");if (a.localeCompare(d) != 0) {document.getElementById("gridgame").appendChild(line);}}}}}
}
function paintpiece(m_piece,color){$("#p"+m_piece).remove();var newSvg=document.getElementById("grid");newSvg.outerHTML+='<div id="p'+m_piece+'" class="divpiece"><svg id="svgp'+m_piece+'" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="280px" height="300px" <viewBox="0 0 100 100"></svg></div>';
var vpiece=document.createElementNS("http://www.w3.org/2000/svg","g");var $vpiece= $(vpiece);$vpiece.attr("id","piece"+m_piece);$vpiece.attr("class","c_piece");$vpiece.attr("fill",color);document.getElementById("svgp"+m_piece).appendChild(vpiece);var colpieces=0;var filpieces=0;var numrec=0;
for (i=0;i<5;i++){for (j=0;j<5;j++){if (window["m"+m_piece][i][j]==1){var rect = document.createElementNS("http://www.w3.org/2000/svg","rect");
rect.setAttributeNS(null,"x",colpieces);rect.setAttributeNS(null,"y", filpieces);rect.setAttributeNS(null,"height",celsize);rect.setAttributeNS(null,"width",celsize);rect.setAttribute("id","r"+numrec.toString()+m_piece);rect.setAttribute("class","c_rect");numrec++;document.getElementById("piece"+m_piece).appendChild(rect);} colpieces=colpieces+celsize;} colpieces=0;filpieces=filpieces+celsize;}
var minfil=6*celsize;for (i=0;i<5;i++){if (parseFloat(document.getElementById("r"+i.toString()+m_piece).getAttribute("y"))<minfil){minfil=parseFloat(document.getElementById("r"+i.toString()+m_piece).getAttribute("y"))}} for (i=0;i<5;i++){document.getElementById("r"+i.toString()+m_piece).setAttributeNS(null,"y",parseFloat(document.getElementById("r"+i.toString()+m_piece).getAttribute("y"))-minfil);}
minfil=6*celsize;for (i=0;i<5;i++){if (parseFloat(document.getElementById("r"+i.toString()+m_piece).getAttribute("x"))<minfil){minfil=parseFloat(document.getElementById("r"+i.toString()+m_piece).getAttribute("x"))}} for (i=0;i<5;i++){document.getElementById("r"+i.toString()+m_piece).setAttributeNS(null,"x",parseFloat(document.getElementById("r"+i.toString()+m_piece).getAttribute("x"))-minfil);}
var maxcol=0;var maxfil=0;var c1=0;var c2=0;var c3=0;var c4=0;var c5=0;for (i=0;i<5;i++){for (j=0;j<5;j++){if (window["m"+m_piece][i][j]==1){if (j==0){c1=1;}if (j==1){c2=1;}if (j==2){c3=1;}if (j==3){c4=1;}if (j==4){c5=1;}}}}
$("#svgp"+m_piece).css("width",(c1+c2+c3+c4+c5)*celsize);
c1=0;c2=0;c3=0;c4=0;c5=0;for (i=0;i<5;i++){for (j=0;j<5;j++){if (window["m"+m_piece][i][j]==1){if (i==0){c1=1;}if (i==1){c2=1;}if (i==2){c3=1;}if (i==3){c4=1;}if (i==4){c5=1;}}}}
$("#svgp"+m_piece).css("height",(c1+c2+c3+c4+c5)*celsize);$("#p"+m_piece).bind("touchstart click", function() {showmenu(m_piece);});$("#p"+m_piece).draggable({});
$("#p"+m_piece).on( "dragstart", function( event, ui ) {valueZ++;$("#p"+m_piece).css("z-index",valueZ);});$("#p"+m_piece).on( "dragstop", function( event, ui ) {fixpiece($(this));});}
function showmenu(m_piece){ var c_r=document.getElementsByClassName("c_rect");for (i=0;i<c_r.length;i++){ c_r[i].setAttributeNS(null,"fill-opacity","1");} $("#lmenu").remove();var newmenu=document.createElement("div");
newmenu.setAttribute("id","lmenu");var pos_left=$("#p"+m_piece).offset().left-$("#svggrid").offset().left-celsize;var pos_top=$("#p"+m_piece).offset().top-$("#svggrid").offset().top+celsize;if (pos_left<0){pos_left=$("#p"+m_piece).width()+celsize}
var brot = $("<input/>").attr({ id: "brp", type:"button", name:"brp", value:"↻"});var bsh = $("<input/>").attr({ id: "bsh", type:"button", name:"bsh", value:"↔"});var bsv = $("<input/>").attr({ id: "bsv", type:"button", name:"bsv", value:"↕"});
$("#ardoraAct").append(newmenu);$("#lmenu").append(brot);$("#lmenu").append(bsh);$("#lmenu").append(bsv);$("#lmenu").offset({left:pos_left,top:pos_top});valueZ++;$("#lmenu").css("z-index",valueZ);$("#lmenu").css("width",celsize);
$("input").css("width",celsize);$("input").css("height",celsize);$("input").css("font-size",celsize-celsize/3);$("#brp").bind("touchstart click", function() {rotatepiece(m_piece);});
$("#bsh").bind("touchstart click", function() {fliph(m_piece);});$("#bsv").bind("touchstart click", function() {flipv(m_piece);});
$("#grid").click(function() {var c_r=document.getElementsByClassName("c_rect");for (i=0;i<c_r.length;i++){c_r[i].setAttributeNS(null,"fill-opacity","1");} $("#lmenu").remove();});for (i=0;i<5;i++){document.getElementById("r"+i.toString()+m_piece).setAttributeNS(null,"fill-opacity","0.5");}}
function fliph(m_piece){clearboard($("#p"+m_piece));var pos_left=$("#p"+m_piece).offset().left;var pos_top=$("#p"+m_piece).offset().top;var grip=window["m"+m_piece];var ngrip=[];for (i=0;i<5;i++){ngrip[i]=new Array(5);}
for (i=0;i<5;i++){ngrip[i][0]=grip[i][4];ngrip[i][4]=grip[i][0];ngrip[i][1]=grip[i][3];ngrip[i][3]=grip[i][1];ngrip[i][2]=grip[i][2];}
window["m"+m_piece]=ngrip;paintpiece(m_piece,document.getElementById("piece"+m_piece).getAttribute("fill"));$("#p"+m_piece).offset({left:pos_left,top:pos_top});writeboard($("#p"+m_piece));}
function flipv(m_piece){clearboard($("#p"+m_piece));var pos_left=$("#p"+m_piece).offset().left;var pos_top=$("#p"+m_piece).offset().top;var grip=window["m"+m_piece];var ngrip=[];for (i=0;i<5;i++){ngrip[i]=new Array(5);}
for (j=0;j<5;j++){ngrip[0][j]=grip[4][j];ngrip[4][j]=grip[0][j];ngrip[1][j]=grip[3][j];ngrip[3][j]=grip[1][j];ngrip[2][j]=grip[2][j];}
window["m"+m_piece]=ngrip;paintpiece(m_piece,document.getElementById("piece"+m_piece).getAttribute("fill"));$("#p"+m_piece).offset({left:pos_left,top:pos_top});writeboard($("#p"+m_piece));}
function rotatepiece(m_piece){clearboard($("#p"+m_piece));var pos_left=$("#p"+m_piece).offset().left;var pos_top=$("#p"+m_piece).offset().top;var grip=window["m"+m_piece];var ngrip=[];for (i=0;i<5;i++){ngrip[i]=new Array(5);}
for (i=0;i<5;i++){for (j=0;j<5;j++){var c=4-i;ngrip[j][c]=grip[i][j];}} window["m"+m_piece]=ngrip;paintpiece(m_piece,document.getElementById("piece"+m_piece).getAttribute("fill"));$("#p"+m_piece).offset({left:pos_left,top:pos_top});writeboard($("#p"+m_piece));}
function fixpiece(piece){clearboard(piece);var pos_left=piece.offset().left-$("#svggrid").offset().left;var pos_top=piece.offset().top-$("#svggrid").offset().top;if (pos_left<0){piece.offset({left:$("#svggrid").offset().left});}if (pos_top<0){piece.offset({top:$("#svggrid").offset().top});}
for (i=0;i<col*celsize;i+=celsize){if (pos_left>=i && pos_left<i+celsize){if ((pos_left-i)<(i+celsize-pos_left)){piece.offset({left:i+$("#svggrid").offset().left});}else{piece.offset({left:i+celsize+$("#svggrid").offset().left});}}}
for (i=0;i<fil*celsize;i+=celsize){if (pos_top>=i && pos_top<i+celsize){if ((pos_top-i)<(i+celsize-pos_top)){piece.offset({top:i+$("#svggrid").offset().top});}else{piece.offset({top:i+celsize+$("#svggrid").offset().top});}}} writeboard(piece);}
function writeboard(piece) {var b_col = Math.round((piece.offset().left - $("#svggrid").offset().left) / celsize);var b_fil = Math.round((piece.offset().top - $("#svggrid").offset().top) / celsize);var m_p = piece.attr("id").substring(1, 300);
for (i = 0; i < 5; i++) {var i_x = parseFloat(document.getElementById("r" + i.toString() + m_p).getAttribute("x"));var i_y = parseFloat(document.getElementById("r" + i.toString() + m_p).getAttribute("y"));if (board[b_fil + (i_y) / celsize][b_col + (i_x) / celsize] == "0") {board[b_fil + (i_y) / celsize][b_col + (i_x) / celsize] = m_p;
} else {board[b_fil + (i_y) / celsize][b_col + (i_x) / celsize] = board[b_fil + (i_y) / celsize][b_col + (i_x) / celsize] + "#" + m_p;}}}
function clearboard(piece){var m_p=piece.attr("id").substring(1,300);for (i=0;i<fil;i++){for (j=0;j<col;j++){if (board[i][j]!="0"){if (board[i][j]==m_p){board[i][j]="0";}else{
if (board[i][j].indexOf(m_p)>-1){if (board[i][j].indexOf(m_p)==0){board[i][j]=board[i][j].replace(m_p,"");}else{board[i][j]=board[i][j].replace("#"+m_p,"");}}}}}}}
function touchHandler(event) {var touch = event.changedTouches[0];var simulatedEvent = document.createEvent("MouseEvent");simulatedEvent.initMouseEvent({touchstart: "mousedown",touchmove: "mousemove",touchend: "mouseup"}[event.type], true, true, window, 1,
touch.screenX, touch.screenY,touch.clientX, touch.clientY, false,false, false, false, 0, null);touch.target.dispatchEvent(simulatedEvent);event.preventDefault();};
function randomSort(){
}
function isCorrect(){var canWidth=$("#ardoraAct").css("width").replace("px","");var canHeight=$("#ardoraAct").css("height").replace("px","");$("#ardoraActCanvas").attr({"width": canWidth,"height": canHeight});$("#ardoraActCanvasAnim").attr({"width": canWidth,"height": canHeight});
var minc=1000;var maxc=0;var minf=1000;var maxf=0;for (i = 0; i < fil; i++) {for (j = 0; j < col; j++) {if (board[i][j] != "0") {if (i<minf){minf=i;}if (i>maxf){maxf=i;}if (j<minc){minc=j;}if (j>maxc){maxc=j;}}}}
var correct=true;if ((maxf-minf+1)!=solh || (maxc-minc+1)!=solw){correct=false;}if (correct){for (i=0; i <solw ; i++) {for (j=0; j <solh; j++) {var a = PentaWords(sol[j][i]).toString().trim();if (a.localeCompare("N") != 0 && board[minf+j][minc+i]=="0") {correct=false;}if (a.localeCompare("N")==0 && board[minf+j][minc+i]!="0") {correct=false;}}}}
if (correct) {score=score+scoreInc;timeAct=timeAct+timeBon;successes++;$("#ardoraActCanvas").attr("aria-label",messageOk); showMessage("Ok");$("#buttonOk").remove();} else {
attempts++;score = score - scoreDec;if (tiAttempts) {if (attempts > attemptsMax) {$("#ardoraActCanvas").attr("aria-label",messageAttempts);showMessage("Attempts");} else {$("#ardoraActCanvas").attr("aria-label", messageError);showMessage("Error");}} else {$("#ardoraActCanvas").attr("aria-label", messageError);showMessage("Error");}};}
function goTime(){clearInterval(timeInterval);showMessage("Time");}
function showSol(oldTypeGame){ 
}
function paintBack(){}
function PentaWords(input) {return decodeURIComponent(escape(window.atob( input )));}
Array.prototype.in_array=function(){ for(var j in this){ if(this[j]==arguments[0]){return true;}}return false;}
